src/OpenModServer/Areas/Admin/Pages/ApprovalManager.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OpenModServer.Areas.Account;
using OpenModServer.Data;
using OpenModServer.Data.Identity;
using OpenModServer.Data.Releases;
using OpenModServer.Data.Releases.Approvals;
using OpenModServer.Services;

namespace OpenModServer.Areas.Admin.Pages;

[Authorize(Policy = nameof(Permissions.ApproveReleases))]
public class ApprovalManager : PageModel
{
    private readonly ApplicationDbContext _database;
    private readonly UserManager<OmsUser> _userManager;
    private readonly FileManagerService _fileManagerService;

    public ModRelease Release { get; set; }
    
    public ApprovalManager(ApplicationDbContext context, FileManagerService fileManagerService, UserManager<OmsUser> userManager)
    {
        _database = context;
        _userManager = userManager;
        _fileManagerService = fileManagerService;
    }
    public async Task<IActionResult> OnGetAsync()
    {
        IActionResult ErrorRedirect() => RedirectToPage("/Mods", new { Area = "Admin" });
        
        if (Guid.TryParse(RouteData.Values["id"]?.ToString(), out var releaseId))
        {
            var release = await _database
                .ModReleases
                .Include(t => t.ApprovalHistory)
                .ThenInclude(t => t.ModeratorResponsible)
                .Include(t => t.ModListing)
                .ThenInclude(c => c.Creator)
                .FirstOrDefaultAsync(d => d.Id == releaseId);
            if (release == null) return ErrorRedirect();
            
            Release = release;
            
            return Page();
        }

        return ErrorRedirect();
    }

    public async Task<IActionResult> HandleStateChangeAsync(string id, ModReleaseApprovalStatus newStatus)
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null || !Guid.TryParse(id, out var releaseId)) return RedirectToPage();
        var release = await _database.ModReleases
            .Include(c =>c.ApprovalHistory)
            .Include(d => d.ModListing)
            .FirstOrDefaultAsync(d => d.Id == releaseId);
        if (release == null) return RedirectToPage();

        if (newStatus == ModReleaseApprovalStatus.Approved) release.ModListing.IsVisibleToPublic = true;
        var originalState = release.CurrentStatus;
        release.CurrentStatus = newStatus;
        release.ApprovalHistory.Add(new ModReleaseApprovalChange
        {
            ModeratorResponsibleId = user.Id,
            Reason = "Actioned in Case Manager",
            CurrentState = newStatus,
            PreviousStatus = originalState
        });

        await _database.SaveChangesAsync();

        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostHandleApprovalAsync(string id)
    {
        return await HandleStateChangeAsync(id, ModReleaseApprovalStatus.Approved);
    }
    
    public async Task<IActionResult> OnPostHandleRejectionAsync(string id)
    {
        return await HandleStateChangeAsync(id, ModReleaseApprovalStatus.DeniedByModerator);
    }

    public async Task<IActionResult> OnPostHandleRequestInformationAsync(string id)
    {
        return await HandleStateChangeAsync(id, ModReleaseApprovalStatus.NeedMoreInformation);
    }

    public async Task<IActionResult> OnPostHandleDeletionAsync(string id)
    {
        if (!Guid.TryParse(id, out var releaseId)) return RedirectToPage();
        var release = await _database.ModReleases.FirstOrDefaultAsync(d => d.Id == releaseId);
        if (release == null) return RedirectToPage();
        _database.ModReleases.Remove(release);

        await _fileManagerService.DeleteModReleaseAsync(release);

        await _database.SaveChangesAsync();
        
        return RedirectToPage();
    }
}

src/OpenModServer/Areas/Admin/Pages/Files.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OpenModServer.Areas.Account;
using OpenModServer.Data;
using OpenModServer.Data.Identity;
using OpenModServer.Data.Releases;
using OpenModServer.Data.Releases.Approvals;
using OpenModServer.Services;

namespace OpenModServer.Areas.Admin.Pages;

[Authorize(Policy=nameof(Permissions.ApproveReleases))]
public class Files : PageModel
{
    public List<ModRelease> Releases { get; set; }
    public List<ModRelease> ModerationQueue { get; set; }

    private readonly UserManager<OmsUser> _userManager;
    private readonly FileManagerService _fileManagerService;

    public Files(ApplicationDbContext context, FileManagerService fileManagerService, UserManager<OmsUser> userManager)
    {
        _database = context;
        _userManager = userManager;
        _fileManagerService = fileManagerService;
    }

    private readonly ApplicationDbContext _database;
    public async Task OnGetAsync()
    {
        ModerationQueue = await _database.ModReleases.Where(d => d.CurrentStatus == ModReleaseApprovalStatus.Unapproved)
            .ToListAsync();
        
        Releases = await _database.ModReleases.Include(c => c.ModListing).ToListAsync();
    }

    public async Task<IActionResult> OnPostHandleDeletionAsync(string id)
    {
        if (!Guid.TryParse(id, out var releaseId)) return RedirectToPage("/Files", new { Area = "Admin" });
        var release = await _database.ModReleases.FirstOrDefaultAsync(d => d.Id == releaseId);
        if (release == null) return RedirectToPage("/Files", new { Area = "Admin" });
        _database.ModReleases.Remove(release);

        await _fileManagerService.DeleteModReleaseAsync(release);

        await _database.SaveChangesAsync();
        
        ModerationQueue = await _database.ModReleases
            .Where(d => d.CurrentStatus == ModReleaseApprovalStatus.Unapproved)
            .ToListAsync();
        
        Releases = await _database.ModReleases.Include(c => c.ModListing).ToListAsync();
        return Page();
    }

    public async Task<IActionResult> OnPostHandleApprovalAsync(string id)
    {
        var userId = Guid.Parse(await _userManager.GetUserIdAsync(await _userManager.GetUserAsync(User)));
        if (!Guid.TryParse(id, out var releaseId)) return RedirectToPage("/Files", new { Area = "Admin" });
        var release = await _database.ModReleases.Include(c =>c.ApprovalHistory).FirstOrDefaultAsync(d => d.Id == releaseId);
        if (release == null) return RedirectToPage("/Files", new { Area = "Admin" });

        var originalState = release.CurrentStatus;
        release.CurrentStatus = ModReleaseApprovalStatus.Approved;
        release.ApprovalHistory.Add(new ModReleaseApprovalChange
        {
            ModeratorResponsibleId = userId,
            Reason = "Approved in admin console",
            CurrentState = ModReleaseApprovalStatus.Approved,
            PreviousStatus = originalState
        });

        await _database.SaveChangesAsync();
        
        ModerationQueue = await _database.ModReleases.Where(d => d.CurrentStatus == ModReleaseApprovalStatus.Unapproved)
            .ToListAsync();
        
        Releases = await _database.ModReleases.Include(c => c.ModListing).ToListAsync();
        return Page();
    }
}

src/OpenModServer/Areas/Admin/Pages/ModerationActions.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OpenModServer.Areas.Account;
using OpenModServer.Data;
using OpenModServer.Data.Identity;
using OpenModServer.Data.Releases.Approvals;
using OpenModServer.Services;

namespace OpenModServer.Areas.Admin.Pages;

[Authorize(Policy = nameof(Permissions.ApproveReleases))]
public class ModerationActions : PageModel
{
    public List<ModReleaseApprovalChange> Changes { get; set; }
    
    private readonly UserManager<OmsUser> _userManager;
    private readonly FileManagerService _fileManagerService;

    public ModerationActions(ApplicationDbContext context, FileManagerService fileManagerService, UserManager<OmsUser> userManager)
    {
        _database = context;
        _userManager = userManager;
        _fileManagerService = fileManagerService;
    }

    private readonly ApplicationDbContext _database;
    public async Task OnGetAsync()
    {
        Changes = await _database.ApprovalChanges
            .Include(c => c.ModeratorResponsible)
            .OrderByDescending(d => d.CreatedAt)
            .Take(100)
            .Include(c => c.ModRelease)
            .ToListAsync();
    }
}

src/OpenModServer/Areas/Admin/Pages/Mods.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OpenModServer.Areas.Account;
using OpenModServer.Data;
using OpenModServer.Data.Identity;
using OpenModServer.Data.Releases;
using OpenModServer.Data.Releases.Approvals;
using OpenModServer.Services;

namespace OpenModServer.Areas.Admin.Pages;

[Authorize(Policy=nameof(Permissions.ManageListings))]
public class Mods : PageModel
{
    public List<ModListing> Listings { get; set; }

    private readonly UserManager<OmsUser> _userManager;
    private readonly FileManagerService _fileManagerService;

    public Mods(ApplicationDbContext context, FileManagerService fileManagerService, UserManager<OmsUser> userManager)
    {
        _database = context;
        _userManager = userManager;
        _fileManagerService = fileManagerService;
    }

    private readonly ApplicationDbContext _database;
    public async Task OnGetAsync()
    {
        Listings = await _database.ModListings.ToListAsync();
    }

    public async Task<IActionResult> OnPostHandleDeletionAsync(string id)
    {
        if (!Guid.TryParse(id, out var listing)) return RedirectToPage("/Files", new { Area = "Admin" });
        var release = await _database.ModListings.FirstOrDefaultAsync(d => d.Id == listing);
        if (release == null) return RedirectToPage("/Files", new { Area = "Admin" });
        _database.ModListings.Remove(release);
        
        await _database.SaveChangesAsync();
        
        Listings = await _database.ModListings.ToListAsync();
        return Page();
    }
}

src/OpenModServer/Areas/Admin/Pages/Status.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OpenModServer.Areas.Account;

namespace OpenModServer.Areas.Admin.Pages;

[Authorize(nameof(Permissions.Administrator))]
public class Status : PageModel
{
    public void OnGet()
    {
        
    }
}

src/OpenModServer/Areas/Admin/Pages/Users.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using OpenModServer.Areas.Account;
using OpenModServer.Data;
using OpenModServer.Data.Identity;
using OpenModServer.Data.Releases;
using OpenModServer.Data.Releases.Approvals;
using OpenModServer.Services;
using OpenModServer.Structures;

namespace OpenModServer.Areas.Admin.Pages;

[Authorize(Policy = nameof(Permissions.Administrator))]
public class Users : PageModel
{
    [Display(Name="Role name")]
    [BindProperty]
    public string RoleName { get; set; }
    
    [Display(Name = "Permissions")]
    [BindProperty]
    public Dictionary<string, bool> RolePermissions { get; set; }
    
    public List<OmsUser> UserAccounts { get; set; }
    public List<IdentityRole<Guid>> Roles { get; set; }
    public List<IdentityUserRole<Guid>> UserRoles { get; set; }
    public List<IdentityRoleClaim<Guid>> RoleClaims { get; set; }

    private readonly UserManager<OmsUser> _userManager;
    private readonly FileManagerService _fileManagerService;
    private readonly RoleManager<OmsRole> _roleManager;

    public Users(ApplicationDbContext context, FileManagerService fileManagerService, UserManager<OmsUser> userManager,
        RoleManager<OmsRole> roleManager)
    {
        _database = context;
        _userManager = userManager;
        _fileManagerService = fileManagerService;
        _roleManager = roleManager;
    }

    private readonly ApplicationDbContext _database;
    public async Task OnGetAsync()
    {
        UserAccounts = await _database.Users.ToListAsync();
        RoleClaims = await _database.RoleClaims.ToListAsync();
        Roles = await _database.Roles.ToListAsync();
        UserRoles = await _database.UserRoles.ToListAsync();
    }

    public async Task<IActionResult> OnPostHandleRoleCreateAsync()
    {
        var role = new OmsRole
        {
            Name = RoleName,
        };
        var createRoleResult = await _roleManager.CreateAsync(role);
        if (!createRoleResult.Succeeded)
        {
            TempData.PutJson("Alert", new TemporaryAlert(
                TemporaryAlertType.Danger,
                "Failed to create role.",
                string.Join(", ", createRoleResult.Errors.Select(d => d.Description))
            ));
            await OnGetAsync();
            return Page();
        }
        
        foreach (var p in RolePermissions.Where(p => p.Value))
        {
            await _roleManager.AddClaimAsync(role, new Claim("Permission", p.Key));
        }

        return RedirectToPage();
    }
}

src/OpenModServer/Areas/Downloads/Controllers/DownloadsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OpenModServer.Areas.Account;
using OpenModServer.Data;
using OpenModServer.Data.Releases.Approvals;

namespace OpenModServer.Areas.Downloads.Controllers;

[Controller, Route("/downloads")]
[Area("Downloads")]
public class DownloadController : Controller
{
    private readonly ILogger<DownloadController> _logger;
    private readonly ApplicationDbContext _database;

    public DownloadController(ILogger<DownloadController> logger, ApplicationDbContext database)
    {
        _database = database;
        _logger = logger;
    }
    
    [HttpGet("releases/{id}")]
    public async Task<IActionResult> DownloadReleaseById([FromRoute] string id)
    {
        if (!Guid.TryParse(id, out var guid)) return BadRequest();
        var release = await _database.ModReleases.Include(c => c.ModListing).FirstOrDefaultAsync(r => r.Id == guid);
        if (release is not { CurrentStatus: ModReleaseApprovalStatus.Approved }) return NotFound();
        release.DownloadCount++;
        release.ModListing.DownloadCount++;
        _ = _database.SaveChangesAsync();
        var stream = System.IO.File.OpenRead(release.FilePath);
        return new FileStreamResult(stream, "application/octet-stream")
        { 
            LastModified = release.CreatedAt,
            FileDownloadName = release.FileName
        };
    }

    [HttpGet("casemanager/files/{id}")]
    [Authorize(Policy=nameof(Permissions.ApproveReleases))]
    public async Task<IActionResult> DownloadCaseManagerFile([FromRoute] string id)
    {
        if (!Guid.TryParse(id, out var guid)) return BadRequest();
        var release = await _database.ModReleases
            .FirstOrDefaultAsync(r => r.Id == guid);
        if (release == null) return NotFound();
        var stream = System.IO.File.OpenRead(release.FilePath);
        return new FileStreamResult(stream, "application/octet-stream")
        { 
            LastModified = release.CreatedAt,
            FileDownloadName = release.FileName
        };
    }
}

src/OpenModServer/Areas/Mods/Pages/Releases/Release.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OpenModServer.Data;
using OpenModServer.Data.Releases;

namespace OpenModServer.Areas.Mods.Pages.Releases;

public class ReleaseModel : PageModel
{
    public ModRelease Release { get; set; }
    private readonly ApplicationDbContext _database;
    private readonly ILogger<ReleaseModel> _logger;
    public ReleaseModel(ILogger<ReleaseModel> logger, ApplicationDbContext database)
    {
        _database = database;
        _logger = logger;
    }
    public async Task OnGet()
    {
        Release = await _database.ModReleases
            .Include(d => d.ApprovalHistory)
            .FirstOrDefaultAsync(d => d.Id == Guid.Parse(RouteData.Values["release_id"].ToString()));
    }
}

src/OpenModServer/Areas/Mods/Pages/Tags/ViewTag.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OpenModServer.Data;
using OpenModServer.Data.Identity;

namespace OpenModServer.Areas.Mods.Pages.Tags;

public class ViewTag : PageModel
{
    private readonly ILogger<ViewAllModsModel> _logger;
    internal List<IGrouping<string, ModListing>>? ModListings;
    private readonly ApplicationDbContext _database;

    public string Name { get; set; }

    public ViewTag(ILogger<ViewAllModsModel> logger, ApplicationDbContext database)
    {
        _database = database;
        _logger = logger;
    }
    public async Task<IActionResult> OnGetAsync()
    {
        var name= RouteData.Values["id"]?.ToString();
        if (string.IsNullOrWhiteSpace(name)) return NotFound();

        Name = name;
        ModListings = await _database.ModListings.Where(m => m.Tags.Contains(Name) && m.IsVisibleToPublic).Take(20)
            .GroupBy(d => d.GameIdentifier).ToListAsync();

        return Page();
    }
}

src/OpenModServer/Areas/Admin/Pages/ApprovalManager.cshtml
@page "/admin/approvals/{id}"
@using Humanizer
@using OpenModServer.Data.Releases.Safety
@model OpenModServer.Areas.Admin.Pages.ApprovalManager

<h1>Case Manager</h1>
<form method="post">
<input type="hidden" name="id" value="@Model.Release.Id" />
<div class="my-4">
    <div class="row mb-3">
        <div class="col">
            <h3>Release info</h3>
            <div>Name: @Model.Release.Name</div>
            <div>Mod: @Model.Release.ModListing.Name</div>
            <div>Type: @Model.Release.ReleaseType</div>
        </div>
        <div class="col">
            <h3>Submitted by</h3>
            <div class="mb-3 border rounded p-2 d-flex flex-row">
                <img class="rounded" src="@($"https://www.gravatar.com/avatar/{Model.Release.ModListing.Creator.GenerateMd5EmailHash()}")" width="50px" height="50px"/>
                <div class="d-flex flex-column ms-2">
                    <a asp-area="Users" asp-page="/User" asp-route-id="@Model.Release.ModListing?.CreatorId">@Model.Release.ModListing?.Creator.UserName</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h3>Changelog</h3>
            <div>@Model.Release.Changelog</div>
        </div>
        <div class="col">
            <h3>Download</h3>
            <div><a asp-area="Downloads" asp-controller="Download" asp-action="DownloadCaseManagerFile" asp-route-id="@Model.Release.Id">@Model.Release.FileName</a> (@Model.Release.FileSizeKilobytes KB)</div>
            <div>VirusTotal scan result: 
                @{
                    switch (Model.Release.VT_ScanResult)
                    {
                        case VirusTotalScanStatus.WaitingOnVirusTotalToComplete:
                            <span class="text-info">Waiting</span>
                            break;
                        case VirusTotalScanStatus.Clean:
                            <span class="text-success">Clean</span>
                            break;
                        case VirusTotalScanStatus.Dirty:
                            <span class="text-danger">@Model.Release.VT_NumberOfMaliciousScans malicious,  @Model.Release.VT_NumberOfSuspiciousScans suspicious</span>
                            break;
                        case null:
                            <span class="text-primary">Not submitted</span>
                            break;
                        default:
                            throw new ArgumentOutOfRangeException();
                    }
                }
            </div>
            <div class="text-muted">Last VT update: @(Model.Release.VT_LastUpdatedAt?.Humanize())</div>
        </div>
    </div>
</div>
<div>
    <h3>Approval history</h3>
    @if(Model.Release.ApprovalHistory.Any())
    {
        <table class="table">
            <thead>
            <tr>
                <th>Date</th>
                <th>State</th>
                <th>Responsible</th>
                <th style="width:400px;">Stated reason</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var history in Model.Release.ApprovalHistory.OrderByDescending(d => d.CreatedAt))
            {
                <tr>
                    <td>@history.CreatedAt (@history.CreatedAt.Humanize())</td>
                    <td>@if (history.IsPrivateNote)
                        {
                            <span>Private note</span>
                        }
                        else
                        {
                            <span>@history.PreviousStatus.Humanize() to @history.CurrentState.Humanize()</span>
                        }</td>
                    <td>@(history.ModeratorResponsible?.UserName ?? "Unknown")</td>
                    <td>@history.Reason</td>
                </tr>
            }
            </tbody>
        </table>
    }
    else
    {
        <div>No history recorded</div>
    }
    <button class="btn btn-secondary">Add private note</button>
    <div class="text-muted">Private notes are only visible to approval moderators.</div>
</div>
<div class="mt-4">
    <h3>Actions</h3>
    <div class="d-flex flex-row">
        <div class="mb-3 card">
            <div class="card-body">
                <h5 class="card-title">Primary</h5>
                <h6 class="card-subtitle mb-3 text-muted">Use these actions to approve or reject releases.</h6>
                <button asp-page-handler="HandleApproval" type="submit" class="btn btn-success">Approve</button>
                <button asp-page-handler="HandleRejection" type="submit" class="btn btn-danger">Reject</button>
            </div>
        </div>
        <div class="mb-3 card">
            <div class="card-body">
                <h5 class="card-title">Pending</h5>
                <h6 class="card-subtitle mb-3 text-muted">Use these actions to delay approval while waiting for more information from the submitter.</h6>
                <button asp-page-handler="HandleRequestInformation" class="btn btn-info">Request more information</button>
            </div>
        </div>
        <div class="mb-3 card">
            <div class="card-body">
                <h5 class="card-title">Deletion</h5>
                <h6 class="card-subtitle mb-3 text-muted">Only use these actions for violations of the User Agreement.</h6>

                <button asp-page-handler="HandleDeletion" class="btn btn-warning">Delete</button>
                <button class="btn disabled btn-outline-danger">Delete and ban submitter</button>
            </div>
        </div>
    </div>
</div>
</form>

src/OpenModServer/Areas/Admin/Pages/Files.cshtml
@page
@model OpenModServer.Areas.Admin.Pages.Files

<div>
    <h3>Moderation queue</h3>
    
    <table class="table">
        <thead>
        <tr>
            <th>
                ID
            </th>
            <th>File name</th>
            <th>Mod name</th>
            <th>Release name</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
            @foreach (var release in Model.ModerationQueue)
            {
                <form method="post">
                    <input type="hidden" name="id" value="@release.Id" />
                    <tr>
                        <td>@release.Id</td>
                        <td>@release.FileName (@release.FileSizeKilobytes KB)</td>
                        <td>@release.ModListing.Name</td>
                        <td>@release.Name</td>
                        <td>@release.CurrentStatus</td>
                        <td>
                            <a asp-area="Admin" asp-page="ApprovalManager" asp-route-id="@release.Id" class="btn btn-sm btn-success">Go to case manager</a>
                            <button asp-page-handler="HandleDeletion" type="submit" class="btn btn-sm btn-danger">Delete</button>
                        </td>
                    </tr>
                </form>
            }
        </tbody>
    </table>
</div>
<div>
    <h3>All files</h3>
    
    <table class="table">
        <thead>
        <tr>
            <th>
                ID
            </th>
            <th>File name</th>
            <th>Mod name</th>
            <th>Release name</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
            @foreach (var release in Model.Releases)
            {
                <form method="post">
                    <input type="hidden" name="id" value="@release.Id" />
                    <tr>
                        <td>@release.Id</td>
                        <td>@release.FileName (@release.FileSizeKilobytes KB)</td>
                        <td>@release.ModListing.Name</td>
                        <td>@release.Name</td>
                        <td>@release.CurrentStatus</td>
                        <td><button asp-page-handler="HandleDeletion" class="btn-sm btn-danger">Delete</button></td>
                    </tr>
                </form>
            }
        </tbody>
    </table>
</div>

src/OpenModServer/Areas/Admin/Pages/ModerationActions.cshtml
@page
@model OpenModServer.Areas.Admin.Pages.ModerationActions

<div>
    <h3>All moderation actions</h3>
    
    <table class="table">
        <thead>
        <tr>
            <th>
                Date
            </th>
            <th>Change</th>
            <th>Responsible mod</th>
            <th>Reason</th>
        </tr>
        </thead>
        <tbody>
            @foreach (var release in Model.Changes)
            {
                <form method="post">
                    <input type="hidden" name="id" value="@release.Id" />
                    <tr>
                        <td>@release.CreatedAt</td>
                        <td>@release.PreviousStatus->@release.CurrentState</td>
                        <td>@(release.ModeratorResponsible?.UserName ?? "System")</td>
                        <td>@release.Reason</td>
                    </tr>
                </form>
            }
        </tbody>
    </table>
</div>

src/OpenModServer/Areas/Admin/Pages/Mods.cshtml
@page
@model OpenModServer.Areas.Admin.Pages.Mods

<div>
    <h3>All listings</h3>
    
    <table class="table">
        <thead>
        <tr>
            <th>
                ID
            </th>
            <th>Name</th>
            <th>Game</th>
            <th>Creator</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
            @foreach (var release in Model.Listings)
            {
                <form method="post">
                    <input type="hidden" name="id" value="@release.Id" />
                    <tr>
                        <td>@release.Id</td>
                        <td>@release.Name</td>
                        <td>@release.GameIdentifier</td>
                        <td>@release.CreatorId</td>
                        <td>
                            <button asp-page-handler="HandleDeletion" type="submit" class="btn-sm btn-danger">Delete</button>
                        </td>
                    </tr>
                </form>
            }
        </tbody>
    </table>
</div>