src/OpenModServer/Areas/Admin/Pages/Mods.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OpenModServer.Areas.Account;
using OpenModServer.Data;
using OpenModServer.Data.Identity;
using OpenModServer.Data.Releases;
using OpenModServer.Data.Releases.Approvals;
using OpenModServer.Services;

namespace OpenModServer.Areas.Admin.Pages;

[Authorize(Policy=nameof(Permissions.ManageListings))]
public class Mods : PageModel
{
    public List<ModListing> Listings { get; set; }

    private readonly UserManager<OmsUser> _userManager;
    private readonly FileManagerService _fileManagerService;

    public Mods(ApplicationDbContext context, FileManagerService fileManagerService, UserManager<OmsUser> userManager)
    {
        _database = context;
        _userManager = userManager;
        _fileManagerService = fileManagerService;
    }

    private readonly ApplicationDbContext _database;
    public async Task OnGetAsync()
    {
        Listings = await _database.ModListings.ToListAsync();
    }

    public async Task<IActionResult> OnPostHandleDeletionAsync(string id)
    {
        if (!Guid.TryParse(id, out var listing)) return RedirectToPage("/Files", new { Area = "Admin" });
        var release = await _database.ModListings.FirstOrDefaultAsync(d => d.Id == listing);
        if (release == null) return RedirectToPage("/Files", new { Area = "Admin" });
        _database.ModListings.Remove(release);
        
        await _database.SaveChangesAsync();
        
        Listings = await _database.ModListings.ToListAsync();
        return Page();
    }
}

src/OpenModServer/Areas/Mods/Pages/Create/Details.cshtml.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Nodes;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OpenModServer.Areas.Games;
using OpenModServer.Areas.Games.Capabilities;
using OpenModServer.Data;
using OpenModServer.Data.Identity;
using OpenModServer.Structures;

namespace OpenModServer.Areas.Mods.Pages;

public class TransitiveModListing
{
     
    [MaxLength(128)]
    [DisplayName("Name")]
    [Display(Prompt = "My new mod")]
    [Required]
    [BindProperty] public string Name { get; set; }
    
    [MaxLength(2048)]
    [DisplayName("Description")]
    [Display(Prompt = "Markdown formatting is supported.")]
    [DataType(DataType.MultilineText)]
    [BindProperty] public string Description { get; set; }

    [DisplayName("Tags")]
    [MaxLength(64)]
    [Display(Prompt = "Separate by commas, i.e. 'fun, difficult, challenge'")]
    [BindProperty]
    public string Tags { get; set; }
    
        
    [MaxLength(128)]
    [DisplayName("Tagline")]
    [Display(Prompt = "A short sentence used in the mod list.")]
    [Required]
    [BindProperty]
    public string Tagline { get; set; }
}
[Authorize]
public class CreateMod : PageModel
{
    [BindProperty] public TransitiveModListing? DataModel { get; set; }
    public MetadataFieldCollectionBuilder? MetadataFields { get; set; }
    public ISupportedGame Game { get; set; }
    
    private readonly ApplicationDbContext _database;
    private readonly UserManager<OmsUser> _userManager;
    private readonly GameManager _gameManager;

    public CreateMod(ApplicationDbContext context, UserManager<OmsUser> userManager, GameManager gameManager)
    {
        _gameManager = gameManager;
        _userManager = userManager;
        _database = context;
    }

    public async Task<IActionResult> OnGetAsync([FromQuery(Name="game")] string gameIdentifier)
    {
        var game = _gameManager.Resolve(gameIdentifier);
        if (game == null)
        {
            return NotFound();
        }

        Game = game;
        if (Game is IMetadataCarrier carrier)
        {
            MetadataFields = new MetadataFieldCollectionBuilder();
            carrier.BuildMetadataFields(MetadataFields);
        }

        return Page();
    }

    public async Task<IActionResult> OnPostAsync([FromQuery(Name="game")] string gameIdentifier)
    {
        if (!ModelState.IsValid || DataModel == null) return Page();

        var game = _gameManager.Resolve(gameIdentifier);
        if (game == null)
        {
            ModelState.AddModelError("Model", "Unknown game.");
            return await OnGetAsync(gameIdentifier);
        }
        var jsonNode = new JsonObject();
        if (game is IMetadataCarrier metadataCarrier)
        {
            var builder = new MetadataFieldCollectionBuilder();
            metadataCarrier.BuildMetadataFields(builder);
            var fields = builder.Fields;
            foreach (var field in fields)
            {
                if (!Request.Form.TryGetValue(field.Key, out var fieldValue) || string.IsNullOrWhiteSpace(fieldValue.ToString()))
                {
                    if (field.Value.FieldType != MetadataFieldType.Boolean)
                    {
                        ModelState.AddModelError(field.Key, $"A response is required for {field.Value.Name}.");
                        continue;
                    }
                    else fieldValue = "off";
                }

                jsonNode[field.Key] = fieldValue.ToString();
            }

            if (!ModelState.IsValid) return await OnGetAsync(gameIdentifier);
        }

        var listing = new ModListing
        {
            CreatorId = Guid.Parse(_userManager.GetUserId(User)!), 
            Name = DataModel.Name,
            Description = DataModel.Description, 
            GameIdentifier = game.Identifier,
            Tagline = DataModel.Tagline,
            GameMetadata = jsonNode
        };
        if (!string.IsNullOrWhiteSpace(DataModel.Tags))
        {
            listing.Tags = DataModel.Tags
                .Split(",")
                .Select(e=>e.Trim())
                .Where(d => !string.IsNullOrWhiteSpace(d))
                .Distinct()
                .ToList();
        }
        _database.ModListings.Add(listing);
        await _database.SaveChangesAsync();
        return RedirectToPage("/Index", new {Area ="Mods",id=listing.Id});
    }
}

src/OpenModServer/Areas/Mods/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OpenModServer.Areas.Account;
using OpenModServer.Data;
using OpenModServer.Data.Comments;
using OpenModServer.Data.Identity;
using OpenModServer.Structures;

namespace OpenModServer.Areas.Mods.Pages;

public class ViewAllModsModel : PageModel
{
    private readonly ILogger<ViewAllModsModel> _logger;
    internal List<IGrouping<string, ModListing>>? ModListings;
    private readonly ApplicationDbContext _database;
    private readonly UserManager<OmsUser> _userManager;

    public ModListing? Listing { get; set; }
    public int ModsMadeByAuthor { get; set; }

    public ViewAllModsModel(ILogger<ViewAllModsModel> logger, ApplicationDbContext database, UserManager<OmsUser> user)
    {
        _database = database;
        _userManager = user;
        _logger = logger;
    }

    public async Task<IActionResult> OnGet()
    {
        if (Guid.TryParse(RouteData.Values["id"]?.ToString(), out var modId))
        {
            var query = await _database.ModListings
                .Include(c => c.Creator)
                .Include(d => d.Releases)
                .Include(c => c.Comments)
                .FirstOrDefaultAsync(d => d.Id == modId);


            if (query == null) return NotFound();
            Listing = query;
            ModsMadeByAuthor = await _database.ModListings.Where(d => d.CreatorId == Listing.CreatorId).CountAsync();

            if (!Listing.IsVisibleToPublic)
            {
                var user = await _userManager.GetUserAsync(User);
                if (user == null) return NotFound();
                if (Listing.CreatorId != user.Id &&
                    !User.HasClaim("Permission", Permissions.ManageListings.ToString("G")))
                    return NotFound();
            }

            return Page();
        }
        
        ModListings = await _database.ModListings
            .Where(c => c.IsVisibleToPublic)
            .Include(e => e.Creator)
            .OrderByDescending(t => t.DownloadCount)
            .Take(50)
            .GroupBy(d => d.GameIdentifier)
            .ToListAsync();
        return Page();
    }
    
    public async Task<IActionResult> OnPostCreateCommentAsync(string modId, string comment)
    {
        var user = await _userManager.GetUserAsync(User);
        if (string.IsNullOrWhiteSpace(modId) || string.IsNullOrWhiteSpace(comment) || user == null)
        {
            return await OnGet();
        }

        _database.Comments.Add(new ModComment
            { AuthorId = user.Id, ModListingId = Guid.Parse(modId), Content = comment });
        await _database.SaveChangesAsync();

        return await OnGet();
    }
}

src/OpenModServer/Areas/Mods/Pages/Releases/CreateRelease.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OpenModServer.Data;
using OpenModServer.Data.Identity;
using OpenModServer.Data.Releases;
using OpenModServer.Data.Releases.Approvals;
using OpenModServer.Services;
using OpenModServer.Services.Safety;
using OpenModServer.Structures;

namespace OpenModServer.Areas.Mods.Pages.Releases;

[Authorize]
public class CreateRelease : PageModel
{
    [BindProperty]
    [MaxLength(64), Required]
    [Display(Prompt = "The version. For example, '1.0'")]
    public string Name { get; set; }
    
    [BindProperty]
    [Required]
    public ModReleaseType Type { get; set; }
    
    [BindProperty]
    [MaxLength(2048)]
    [Required]
    [Display(Prompt = "Use this section to talk about the changes in this version.")]
    public string Changelog { get; set; }
    
    [BindProperty]
    [Required]
    public IFormFile UploadedFile { get; set; }
    
    [BindProperty]
    [Required]
    [RegularExpression("(True|true)", ErrorMessage = "You must agree to the User Agreement.")]
    public bool AgreementChecked { get; set; }

    private readonly FileManagerService _fileManager;
    private readonly ApplicationDbContext _database;
    private readonly UserManager<OmsUser> _userManager;
    private readonly ExternalScanningService _externalScanningService;

    public CreateRelease(FileManagerService fileManager, 
        ApplicationDbContext context, 
        UserManager<OmsUser> manager,
        ExternalScanningService externalScanningService)
    {
        _externalScanningService = externalScanningService;
        _database = context;
        _fileManager = fileManager;
        _userManager = manager;
    }

    public async Task<IActionResult> OnPostAsync()
    {
        var user = Guid.Parse(_userManager.GetUserId(User));
        if (ModelState.IsValid)
        {
            if (Guid.TryParse(RouteData.Values["mod_id"]?.ToString(), out var modId))
            {
                var mod = await _database.ModListings.FirstOrDefaultAsync(d => d.Id == modId && d.CreatorId == user);
                if (mod == null)
                {
                    ModelState.AddModelError("Authorization", "That mod doesn't exist.");
                    return Page();
                }
                
                var file = await _fileManager.AcceptIncomingReleaseUploadAsync(UploadedFile);

                if (file == null) return BadRequest();

                var release = new ModRelease
                {
                    ModListingId = modId,
                    Name = Name,
                    Changelog = Changelog,
                    DownloadCount = 0,
                    FileName = file.Name,
                    FilePath = file.Path,
                    FileSizeKilobytes = file.SizeKilobytes,
                    ReleaseType = Type,
                    CurrentStatus = ModReleaseApprovalStatus.Unapproved
                };
                _database.ModReleases.Add(release);
                await _database.SaveChangesAsync();
                
                await _externalScanningService.EnqueueReleaseForScanningAsync(release);
                Console.WriteLine(release.VT_AnalysisId);
                
                this.SetAlert(new TemporaryAlert(TemporaryAlertType.Success,
                    "Release created",
                    "Congratulations on posting a new release. Once approved, it will be available for users to download."));
                return RedirectToPage($"/Index", new { id = modId, area="Mods"});
            } else return Page();
        }
        else return Page();
    }
}

src/OpenModServer/Areas/Mods/Pages/Releases/Release.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OpenModServer.Data;
using OpenModServer.Data.Releases;

namespace OpenModServer.Areas.Mods.Pages.Releases;

public class ReleaseModel : PageModel
{
    public ModRelease Release { get; set; }
    private readonly ApplicationDbContext _database;
    private readonly ILogger<ReleaseModel> _logger;
    public ReleaseModel(ILogger<ReleaseModel> logger, ApplicationDbContext database)
    {
        _database = database;
        _logger = logger;
    }
    public async Task OnGet()
    {
        Release = await _database.ModReleases
            .Include(d => d.ApprovalHistory)
            .FirstOrDefaultAsync(d => d.Id == Guid.Parse(RouteData.Values["release_id"].ToString()));
    }
}

src/OpenModServer/Areas/Mods/Pages/Tags/ViewTag.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OpenModServer.Data;
using OpenModServer.Data.Identity;

namespace OpenModServer.Areas.Mods.Pages.Tags;

public class ViewTag : PageModel
{
    private readonly ILogger<ViewAllModsModel> _logger;
    internal List<IGrouping<string, ModListing>>? ModListings;
    private readonly ApplicationDbContext _database;

    public string Name { get; set; }

    public ViewTag(ILogger<ViewAllModsModel> logger, ApplicationDbContext database)
    {
        _database = database;
        _logger = logger;
    }
    public async Task<IActionResult> OnGetAsync()
    {
        var name= RouteData.Values["id"]?.ToString();
        if (string.IsNullOrWhiteSpace(name)) return NotFound();

        Name = name;
        ModListings = await _database.ModListings.Where(m => m.Tags.Contains(Name) && m.IsVisibleToPublic).Take(20)
            .GroupBy(d => d.GameIdentifier).ToListAsync();

        return Page();
    }
}

src/OpenModServer/Pages/Mod.cshtml.cs
using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OpenModServer.Data;
using OpenModServer.Structures;

namespace OpenModServer.Pages;

public class Mod : PageModel
{
    [NotNull]
    public ModListing? Listing { get; set; }
    private readonly ApplicationDbContext _database;
    private readonly ILogger<Mod> _logger;
    public Mod(ILogger<Mod> logger, ApplicationDbContext database)
    {
        _database = database;
        _logger = logger;
    }
    public async Task<IActionResult> OnGet()
    {
        if (!Guid.TryParse(RouteData.Values["id"]?.ToString(), out var guid)) return NotFound();
        var query = await _database.ModListings
            .Include(c => c.Creator)
            .Include(d => d.Releases)
            .ThenInclude(d => d.ApprovalHistory)
            .FirstOrDefaultAsync(d => d.Id == guid);
        if (query == null) return NotFound();
        Listing = query;
        return Page();
    }
}

src/OpenModServer/Areas/Mods/Pages/Index.cshtml
@page "{id:guid?}"
@inject GameManager GameManager
@using Humanizer
@using Microsoft.AspNetCore.Html
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using OpenModServer.Areas.Games
@using OpenModServer.Areas.Games.Capabilities
@using OpenModServer.Data.Identity
@using OpenModServer.Data.Releases.Approvals
@using OpenModServer.Structures
@using Westwind.AspNetCore.Markdown
@model OpenModServer.Areas.Mods.Pages.ViewAllModsModel
@inject SignInManager<OmsUser> SignInManager
@inject UserManager<OmsUser> UserManager
@inject OmsConfig Config
@inject LinkGenerator LinkGenerator

<style>
    .card:hover {
        background-color: #f5f5f5;
    }
</style>
<link rel="stylesheet" href="~/@(nameof(Index)).styles.css" />
@if (Model.Listing == null)
{
    ViewData["Title"] = "Mods";
    
    <h1>@ViewData["Title"]</h1>

    foreach (var group in Model.ModListings)
    {
        <div class="mb-4">
            <h3>@(GameManager.Resolve(group.Key)?.Name ?? group.Key)</h3>
            <div class="mt-1 row row-cols-1 row-cols-md-3 g-4">
                @foreach (var listing in group)
                {
                    <div class="col">
                        @await Component.InvokeAsync("ListingCard", listing)
                    </div>
                }         
            </div>
        </div>
    }   
}
else
{
    var isPublishable = GameManager.Resolve(Model.Listing.GameIdentifier) is IPublishable publisher;
    ViewData["Title"] = Model.Listing.Name;
    var game = GameManager.Resolve(Model.Listing!.GameIdentifier);
    var isOwner = SignInManager.IsSignedIn(User) && SignInManager.UserManager.GetUserId(User) == Model.Listing?.CreatorId.ToString();
    var isOwnerOrAdmin = isOwner;
    
    @section Head {
        <meta property="og:title" content="@Model.Listing.Name">
        <meta property="og:site_name" content="@Config.Branding.Name">
        <meta property="og:url" content="@LinkGenerator.GetUriByPage(Model.HttpContext, "Index", values: new { Area="mods", id = Model.Listing.Id })">
        <meta property="og:description" content="@Model.Listing.Tagline">
        <meta property="og:type" content="object">
        <meta property="og:image" content="">
    }
    
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-area="Mods" asp-page="/Index" asp-route-id="">Home</a></li>
            <li class="breadcrumb-item"><a asp-area="Games" asp-page="Index" asp-route-id="@game.Identifier">@game.Name</a></li>
            <li class="breadcrumb-item active" aria-current="page">@Model.Listing.Name</li>
        </ol>
    </nav>
    
    @if (!Model.Listing.IsVisibleToPublic)
    {
        <div class="alert alert-warning" role="alert">
            <h4 class="alert-heading">Awaiting approval</h4>
            <p>
                This mod is awaiting approval. <br />
                It is not visible to the public or listed in the mod lists.
            </p>
            <hr>
            <p class="mb-0">You must submit a first release before a moderator can approve this mod.</p>
        </div>     
    }
    <h2>@Model.Listing?.Name</h2>
                            
    <div>
        Tags:
        @foreach (var tag in Model.Listing.Tags)
        {
            <a asp-area="Mods" asp-page="/Tags/ViewTag" asp-route-id="@tag" class="badge bg-primary">@tag</a>
        }
    </div>
    

    var latestProductionApprovedRelease = Model.Listing?.Releases
        .OrderByDescending(d => d.CreatedAt)
        .FirstOrDefault(d => d.CurrentStatus == ModReleaseApprovalStatus.Approved);
    if (latestProductionApprovedRelease != null)
    {
        <div style="margin-top: 20px; margin-bottom: 30px;">
            <a class="btn btn-lg btn-success" asp-area="Downloads" asp-controller="Download" asp-action="DownloadReleaseById" asp-route-id="@latestProductionApprovedRelease.Id">
                Download latest version <span style="font-size: small">@latestProductionApprovedRelease.Name</span>
            </a>
        </div>
    }
    
    <div style="margin-top: 20px;" class="container">
        <div class="row">
            <div class="mb-3 col-sm-4">
                <div class="mb-3 border rounded p-2 d-flex flex-row">
                    <img class="rounded" src="@($"https://www.gravatar.com/avatar/{Model.Listing.Creator.GenerateMd5EmailHash()}")" width="50px" height="50px" />
                    <div class="d-flex flex-column ms-2">
                        <a asp-area="Users" asp-page="/User" asp-route-id="@Model.Listing?.CreatorId">@Model.Listing?.Creator.UserName</a>
                        <div>@Model.ModsMadeByAuthor mods</div>
                    </div>
                </div>
                <div>
                    <h3>Releases</h3>
                    <div>
                        @foreach (var release in Model.Listing?.Releases.OrderByDescending(d => d.CreatedAt))
                        {
                            <div class="rounded border mb-2 p-2">
                                <div class="d-flex flex-row justify-content-between">
                                    <div>
                                        <div><span style="font-size: large; font-weight: bold;">@release.Name</span> (@release.ReleaseType)</div>
                                        <div style="font-size:small">@release.DownloadCount downloads, @release.FileSizeKilobytes KB</div>
                                        <div style="font-size:small">@release.CreatedAt.Humanize(null, DateTime.Now)</div>
                                    </div>
                                    <div>
                                        @if (release.CurrentStatus == ModReleaseApprovalStatus.Approved)
                                        {
                                            <div><a asp-area="Downloads" asp-controller="Download" asp-action="DownloadReleaseById" asp-route-id="@release.Id">Download</a></div>
                                        }
                                        else
                                        {
                                            <span>Awaiting approval</span>
                                        }
                                    </div>
                                </div>
                            </div>
                        }
                        @if (isOwner)
                        {
                            <a style="text-decoration: none; color: unset;" class="card"  asp-route-mod_id="@Model.Listing?.Id.ToString()" asp-area="Mods" asp-page="/Releases/CreateRelease">
                                <div class="card-body text-center">
                                    Create new release
                                </div>
                            </a>
                        }
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" href="#" data-bs-toggle="tab" data-bs-target="#description">Description</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-bs-toggle="tab" data-bs-target="#comments">Comments (@Model.Listing.Comments.Count)</a>
                    </li>
                    @if (isPublishable)
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="#" data-bs-toggle="tab" data-bs-target="#installation">Installation guide</a>
                        </li>
                    }
                </ul>
                <div class="tab-content mt-3" id="tab-content">
                    <div class="tab-pane fade show active" id="description">
                        @(new HtmlString(new MarkdownParserMarkdig().Parse(@Model.Listing?.Description)))
                    </div>
                    <div class="tab-pane fade " id="comments">

                        @* @if (Model.Listing.Comments.FirstOrDefault(d => d.Id == Model.Listing.PinnedCommentId) is {} pinnedComment) *@
                        @* { *@
                        @*     <div class="d-flex flex-row border border-success rounded p-2 mb-3"> *@
                        @*         <img class="rounded" src="@($"https://www.gravatar.com/avatar/{pinnedComment.Author.GenerateMd5EmailHash()}")" height="50px" width="50px" alt="@pinnedComment.Author.UserName"/> *@
                        @*         <div class="ms-2 w-100"> *@
                        @*             <div class="d-flex flex-row justify-content-between"> *@
                        @*                 <div> *@
                        @*                     <a class="comment-author-title" asp-route-id="@pinnedComment.AuthorId.ToString()" asp-area="Users" asp-page="/User"> *@
                        @*                         @pinnedComment.Author.UserName *@
                        @*                     </a> *@
                        @*                     <span class="ms-2 badge bg-success">Pinned</span> *@
                        @*                     @if (pinnedComment.AuthorId == Model.Listing.CreatorId) *@
                        @*                     { *@
                        @*                         <span class="ms-2 badge bg-info">Author</span> *@
                        @*                     } *@
                        @*                 </div> *@
                        @*                 <div class="text-muted"> *@
                        @*                     @pinnedComment.CreatedAt.Humanize() *@
                        @*                 </div> *@
                        @*             </div> *@
                        @*             <div>@(new HtmlString(new MarkdownParserMarkdig().Parse(pinnedComment.Content)))</div> *@
                        @*         </div> *@
                        @*     </div> *@
                        @* } *@
                        @* @foreach (var comment in Model.Listing.Comments.Where(d => d.Id != Model.Listing.PinnedCommentId)) *@
                        @foreach (var comment in Model.Listing.Comments)
                        {
                            <div class="d-flex flex-row border rounded p-2 mb-2">
                                <img class="rounded" src="@($"https://www.gravatar.com/avatar/{comment.Author.GenerateMd5EmailHash()}")" height="50px" width="50px" alt="@comment.Author.UserName"/>
                                <div class="ms-2 w-100">
                                    <div class="d-flex flex-row justify-content-between">
                                        <div>
                                            <a class="comment-author-title" asp-route-id="@comment.AuthorId.ToString()" asp-area="Users" asp-page="/User">
                                                @comment.Author.UserName
                                            </a>
                                            @if (comment.AuthorId == Model.Listing.CreatorId)
                                            {
                                                <span class="ms-2 badge bg-info">Author</span>
                                            }
                                        </div>
                                        <div class="text-muted">
                                            @comment.CreatedAt.Humanize()
                                        </div>
                                    </div>
                                    <div>@(new HtmlString(new MarkdownParserMarkdig().Parse(comment.Content)))</div>
                                </div>
                            </div>
                        }
                        @if (SignInManager.IsSignedIn(User))
                        {
                            var user = await UserManager.GetUserAsync(User);
                            if (user != null)
                            {
                                <div class="d-flex flex-row w-100">
                                    <img class="rounded" src="@($"https://www.gravatar.com/avatar/{user.GenerateMd5EmailHash()}")" height="50px" width="50px" alt="@user.UserName"/>
                                    <div class="ms-2">
                                        <form method="post">
                                            <input type="hidden" name="modId" value="@Model.Listing.Id" />
                                            <textarea name="comment" class="form-control mb-2" placeholder="Post a new comment..."></textarea>
                                            <button asp-page-handler="CreateComment" type="submit" class="btn btn-success">Post</button>
                                        </form>
                                    </div>
                                </div> 
                            }
                        }
                    </div>
                    @if (isPublishable)
                    {
                        var url = GameManager.GeneratePublisherUrl(game, Model.HttpContext);
                        
                        <div class="tab-pane fade " id="installation">
                            <div>
                                Add the following URL to your plugin sources:
                                <br/>
                                <code>
                                    @url
                                </code>
                                <button type="button" class="btn btn-secondary" onclick="navigator.clipboard.writeText('@url')">Copy</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
}